### ISSUE TITLE
I am working on a awesome-python-htmx, seeking your feedback

### ISSUE THREAD

**Issue by benjamin-kirkbride** [maces/fastapi-htmx#1]
A few of us at PyCon this year got together and brainstormed a new Web Stack that we are calling PyHAT (Python, htmx, ASGI, TailwindCSS). The first thing we set out to do is create [awesome-python-htmx](https://github.com/PyHAT-stack/awesome-python-htmx/blob/main/README.md); a collection of active tools/libraries/projects in that space.

Your project seems like an obvious thing to include, so I did. I'd appreciate your feedback if you have any on it's inclusion.

In addition to that, if you could also participate in https://github.com/PyHAT-stack/awesome-python-htmx/discussions/1 that would be greatly appreciated!

**Comment by maces** [comment]
Hi there,

thanks for including me. 
Will have look  :)
